name: preprocessing
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - cython
  - psutil
  - seqtk
  - fastqc=0.11.9
  - jq
  - pip
  - pip:
      - git+https://github.com/wjlim/dedup_rate_predict.git
      - matplotlib
      - pandas
