name: seGMM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.9
  - r-base >= 3.5
  - r-mclust
  - plink >=1.9
  - samtools >=1.9
  - mosdepth
  - parallel
  - pip
  - pip:
      - seGMM